"""R9 golden values: legacy candidate and stable paths stay byte-identical for 0.x.

The golden JSON fixture was generated by running legacy_outputs() against the module recorded at
commit c341940 (`git show c341940:scripts/release_artifacts.py`, loaded from a
scratch copy), before the new-model release work began. The harness drives the
legacy CLI entry points and helpers with deterministic inputs and a fake build
step, so the values do not depend on the installed build backend. The real
uv build path is covered by the differential test in test_release_artifacts.py.
"""
from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import sys
import zipfile
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from types import ModuleType

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "release_artifacts.py"
SOURCE_SHA = "a" * 40
_DATE = (2020, 1, 1, 0, 0, 0)

GOLDEN_PATH = ROOT / "tests" / "fixtures" / "release_artifacts_r9_golden.json"


def _load(path: Path, name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _wheel(path: Path, version: str) -> Path:
    info = f"data_olympus-{version}.dist-info"
    entries = {
        "data_olympus/__init__.py": b'VALUE = "unchanged"\n',
        f"{info}/METADATA": (
            f"Metadata-Version: 2.4\nName: data-olympus\nVersion: {version}\n"
            "Requires-Dist: pyyaml>=6\n\nBody text\n"
        ).encode(),
        f"{info}/WHEEL": b"Wheel-Version: 1.0\nGenerator: fixture\n",
        f"{info}/entry_points.txt": b"[console_scripts]\nkb = data_olympus.cli:main\n",
    }
    record = "".join(
        f"{name},sha256={hashlib.sha256(data).hexdigest()},{len(data)}\n"
        for name, data in entries.items()
    ) + f"{info}/RECORD,,\n"
    entries[f"{info}/RECORD"] = record.encode()
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, data in entries.items():
            archive.writestr(zipfile.ZipInfo(name, date_time=_DATE), data)
    return path


def _sdist(path: Path, version: str) -> Path:
    path.write_bytes(f"sdist fixture {version}\n".encode())
    return path


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def legacy_outputs(module: ModuleType, root: Path, monkeypatch) -> dict[str, str]:
    """Drive every legacy entry point with 0.x inputs and hash what it emits."""
    outputs: dict[str, str] = {}

    def fake_build(_source: Path, version: str, output: Path):
        output.mkdir(parents=True, exist_ok=True)
        wheel = _wheel(output / f"data_olympus-{version}-py3-none-any.whl", version)
        sdist = _sdist(output / f"data_olympus-{version}.tar.gz", version)
        return module.BuildReceipt(
            version=version, source_sha=SOURCE_SHA, source_tree_sha256="b" * 64,
            lock_sha256="c" * 64, wheel=wheel, sdist=sdist,
            wheel_sha256=_sha(wheel), sdist_sha256=_sha(sdist),
        )

    monkeypatch.setattr(module, "build_distribution", fake_build)
    monkeypatch.setattr(module, "_source_sha", lambda _source: SOURCE_SHA)

    for base, number in (("0.6.0", 3), ("0.11.1", 1), ("0.0.1", 12)):
        identity = module.CandidateVersion.from_base(base, number)
        outputs[f"identity-{base}-{number}"] = repr(
            (identity.base, identity.number, identity.git_tag, identity.pypi_version,
             identity.stable_tag),
        )
        work = root / f"{base}-{number}"
        dist = work / "dist"
        candidate_provenance = work / "candidate.json"
        assert module.main([
            "candidate", "--source", str(work), "--base", base, "--number", str(number),
            "--output", str(dist), "--provenance", str(candidate_provenance),
        ]) == 0
        candidate_wheel = dist / f"data_olympus-{identity.pypi_version}-py3-none-any.whl"
        stable_provenance = work / "stable.json"
        assert module.main([
            "stable", "--source", str(work), "--base", base, "--output", str(dist),
            "--candidate-provenance", str(candidate_provenance),
            "--candidate-wheel", str(candidate_wheel),
            "--provenance", str(stable_provenance),
        ]) == 0
        final = work / "final.json"
        assert module.main([
            "finalize-candidate", "--provenance", str(candidate_provenance),
            "--output", str(final), "--source-sha", SOURCE_SHA,
            "--candidate-tag", identity.git_tag, "--image-digest", "sha256:" + "d" * 64,
        ]) == 0
        for path in (candidate_provenance, stable_provenance, final, *sorted(dist.iterdir())):
            outputs[f"{base}-{number}/{path.relative_to(work).as_posix()}"] = _sha(path)
        receipt = module.compare_wheels(
            candidate_wheel, dist / f"data_olympus-{base}-py3-none-any.whl",
        )
        outputs[f"compare-{base}-{number}"] = repr(sorted(
            (key, getattr(receipt, key)) for key in receipt.__dataclass_fields__
        ))

    for name in ("data_olympus-0.6.0rc3.dist-info/RECORD", "data_olympus/x.py",
                 "data_olympus-0.6.0.dist-info"):
        outputs[f"dist-info-path/{name}"] = module._normalize_dist_info_path(name)
    record = io.StringIO()
    record.write("data_olympus-0.6.0rc3.dist-info/METADATA,sha256=x,1\n")
    record.write("data_olympus/z.py,sha256=y,2\ndata_olympus/a.py,sha256=z,3\n\n")
    outputs["normalize-record"] = module._normalize_record(record.getvalue().encode()).hex()
    outputs["normalize-metadata"] = module._normalize_metadata(
        b"Name: data-olympus\nVersion: 0.6.0rc3\nSummary: Version: kept\n",
    ).hex()
    return outputs


def test_r9_legacy_paths_match_c341940_golden(tmp_path: Path, monkeypatch) -> None:
    module = _load(SCRIPT, "release_artifacts_r9_current")
    golden = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
    assert len(golden) == 32
    assert legacy_outputs(module, tmp_path, monkeypatch) == golden


@pytest.mark.parametrize(("base", "number"), [("0.6.0", 0), ("0.6", 1), ("v0.6.0", 1)])
def test_r9_legacy_candidate_cli_keeps_rejecting_bad_input(
    tmp_path: Path, base: str, number: int,
) -> None:
    module = _load(SCRIPT, "release_artifacts_r9_reject")
    with pytest.raises(ValueError):
        module.main([
            "candidate", "--source", str(tmp_path), "--base", base, "--number", str(number),
            "--output", str(tmp_path / "dist"), "--provenance", str(tmp_path / "p.json"),
        ])
